name: ci

on: [pull_request]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest

    steps:
      - name: Pull code
        uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install project dependencies
        run: yarn install --frozen-lockfile

      - name: Run Eslint
        run: npx eslint --max-warnings 0 .

      - name: Build project
        run: yarn build
